### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by zjh3029** [Eugeny/terminus-save-output#3]
Hi!
**It can not stopped in the console,  I try it many times in windows.   And the terminus' version is  1.09?**
Can I know why?

**Comment by AlexGrok** [comment]
It seems there is no way to stop it – so this plugin does really nothing. User may start it and… that`s it. Just error in DevTools appears: 
![image](https://user-images.githubusercontent.com/32612853/67771069-9d0e1780-fa68-11e9-83a1-c20a548d48a4.png)

**Comment by Eugeny** [comment]
Fixed in v1.0.2

**Comment by AlexGrok** [comment]
@Eugeny thanks a lot! Now it works as it should – just verified.
